### ISSUE TITLE
Install local rainbow and run example not working

### ISSUE THREAD

**Issue by lior-schachter** [Natural-Intelligence/rainbow#50]
I installed rainbow - using this command:
pip install git+https://github.com/Natural-Intelligence/rainbow.git@rainbow_local_mode

running rainbow deploy. Got this error:
MacBook-Pro:dags lior.schachter$ rainbow deploy
Loading image builder implementations..
Finished loading image builder implementations: {'rainbow.build.image.python.python.PythonImageBuilder': <class 'rainbow.build.image.python.python.PythonImageBuilder'>}
Loading service image builder implementations..
Traceback (most recent call last):
  File "/usr/local/bin/rainbow", line 26, in <module>
    from rainbow.build import build_rainbows
  File "/usr/local/lib/python3.7/site-packages/rainbow/build/build_rainbows.py", line 112, in <module>
    ServiceImageBuilderMixin)
  File "/usr/local/lib/python3.7/site-packages/rainbow/core/util/class_util.py", line 30, in find_subclasses_in_packages
    module_content.update(import_module(p))
  File "/usr/local/lib/python3.7/site-packages/rainbow/core/util/class_util.py", line 62, in import_module
    results.update(import_module(full_name))
  File "/usr/local/lib/python3.7/site-packages/rainbow/core/util/class_util.py", line 60, in import_module
    results[full_name] = importlib.import_module(full_name)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.7/site-packages/rainbow/build/service/python_server/rainbow_python_server.py", line 20, in <module>
    from flask import Flask
  File "/usr/local/lib/python3.7/site-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 69, in <module>
    from .wrappers import Request
  File "/usr/local/lib/python3.7/site-packages/flask/wrappers.py", line 14, in <module>
    from werkzeug.wrappers.json import JSONMixin as _JSONMixin
ModuleNotFoundError: No module named 'werkzeug.wrappers.json'; 'werkzeug.wrappers' is not a package

I used the hello_world DAG from the readme file. see attached.
[hello_rainbow.yml.LOG](https://github.com/Natural-Intelligence/rainbow/files/4676832/hello_rainbow.yml.LOG)

**Comment by lior-schachter** [comment]
That's the error I had in the first install:
ERROR: flask 1.1.1 has requirement Werkzeug>=0.15, but you'll have werkzeug 0.14.1 which is incompatible.

I don't get it when rerun install.

**Comment by lior-schachter** [comment]
After running:
pip install -U Werkzeug

I now get a different error:Loading image builder implementations..
Finished loading image builder implementations: {'rainbow.build.image.python.python.PythonImageBuilder': <class 'rainbow.build.image.python.python.PythonImageBuilder'>}
Loading service image builder implementations..
Finished loading service image builder implementations: {'rainbow.build.service.python_server.python_server.PythonServerImageBuilder': <class 'rainbow.build.service.python_server.python_server.PythonServerImageBuilder'>}
deploying rainbow yaml files
WARN: refreshing rainbow core package
/Users/lior.schachter/dev/projects/rainbow/home
running from  /Users/lior.schachter/dev/projects/rainbow/dags
target path for rainbow zip file is  /Users/lior.schachter/dev/projects/rainbow/home
cleaning up the temp dirs /var/folders/sl/t4bb3syx4gx7lc3lwy1y4kn56g8jdc/T//rainbow_build
creating temp directory /var/folders/sl/t4bb3syx4gx7lc3lwy1y4kn56g8jdc/T/rainbow_build-.ZQMNHrMV
/usr/local/bin/package.sh: line 22: wget: command not found
/usr/local/bin/package.sh: line 23: wget: command not found
/usr/local/bin/package.sh: line 24: wget: command not found
cp: docker-compose.yml: No such file or directory
/usr/local/bin/package.sh: line 28: virtualenv: command not found
/usr/local/bin/package.sh: line 29: /var/folders/sl/t4bb3syx4gx7lc3lwy1y4kn56g8jdc/T/rainbow_build-.ZQMNHrMV/venv/bin/activate: No such file or directory
Collecting git+https://github.com/Natural-Intelligence/rainbow.git@rainbow_local_mode
  Cloning https://github.com/Natural-Intelligence/rainbow.git (to revision rainbow_local_mode) to /private/var/folders/sl/t4bb3syx4gx7lc3lwy1y4kn56g8jdc/T/pip-req-build-vrq9ae_q
  Running command git clone -q https://github.com/Natural-Intelligence/rainbow.git /private/var/folders/sl/t4bb3syx4gx7lc3lwy1y4kn56g8jdc/T/pip-req-build-vrq9ae_q
  Running command git checkout -b rainbow_local_mode --track origin/rainbow_local_mode
  Switched to a new branch 'rainbow_local_mode'
  Branch 'rainbow_local_mode' set up to track remote branch 'rainbow_local_mode' from 'origin'.
Building wheels for collected packages: rainbow
  Building wheel for rainbow (setup.py) ... done
  Stored in directory: /private/var/folders/sl/t4bb3syx4gx7lc3lwy1y4kn56g8jdc/T/pip-ephem-wheel-cache-90drn33u/wheels/f4/36/28/2f79221c0a311fbc25cb94e3717b8fab0e9ccf02c318f47824
Successfully built rainbow
Installing collected packages: rainbow
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 414, in run
    use_user_site=options.use_user_site,
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 58, in install_given_reqs
    **kwargs
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 920, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 448, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/wheel.py", line 320, in move_wheel_files
    prefix=prefix,
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/locations.py", line 180, in distutils_scheme
    i.finalize_options()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/install.py", line 248, in finalize_options
    "must supply either home or prefix/exec-prefix -- not both")
distutils.errors.DistutilsOptionError: must supply either home or prefix/exec-prefix -- not both
WARNING: You are using pip version 19.1.1, however version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
pip install --target="/var/folders/sl/t4bb3syx4gx7lc3lwy1y4kn56g8jdc/T/rainbow_build-.ZQMNHrMV/zip_content" -r /var/folders/sl/t4bb3syx4gx7lc3lwy1y4kn56g8jdc/T/rainbow_build-.ZQMNHrMV/zip_content/requirements-airflow.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/var/folders/sl/t4bb3syx4gx7lc3lwy1y4kn56g8jdc/T/rainbow_build-.ZQMNHrMV/zip_content/requirements-airflow.txt'
WARNING: You are using pip version 19.1.1, however version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
/usr/local/bin/package.sh: line 36: my_requirements: command not found
rm: __init__.py: No such file or directory
  adding: hello_rainbow.yml.LOG (deflated 70%)
  adding: hello_rainbow.yml (deflated 70%)
/Users/lior.schachter/dev/projects/rainbow/dags

Getting closer. please advise...

**Comment by lior-schachter** [comment]
I installed Anconda. Seems install process finished with no error.
However, 'rainbow deploy' still doesn't work:
Interesting lines:
/usr/local/bin/package.sh: line 22: wget: command not found
/usr/local/bin/package.sh: line 23: wget: command not found
/usr/local/bin/package.sh: line 24: wget: command not found
cp: docker-compose.yml: No such file or directory
/usr/local/bin/package.sh: line 28: virtualenv: command not found
/usr/local/bin/package.sh: line 29: 

Full log:
(base) pc-clementcohen:dags lior.schachter$ rainbow deploy
Loading image builder implementations..
Finished loading image builder implementations: {'rainbow.build.image.python.python.PythonImageBuilder': <class 'rainbow.build.image.python.python.PythonImageBuilder'>}
Loading service image builder implementations..
Finished loading service image builder implementations: {'rainbow.build.service.python_server.python_server.PythonServerImageBuilder': <class 'rainbow.build.service.python_server.python_server.PythonServerImageBuilder'>}
deploying rainbow yaml files
WARN: refreshing rainbow core package
/Users/lior.schachter/dev/projects/liminal/home
running from  /Users/lior.schachter/dev/projects/liminal/dags
target path for rainbow zip file is  /Users/lior.schachter/dev/projects/liminal/home
cleaning up the temp dirs /var/folders/sl/t4bb3syx4gx7lc3lwy1y4kn56g8jdc/T//rainbow_build
creating temp directory /var/folders/sl/t4bb3syx4gx7lc3lwy1y4kn56g8jdc/T/rainbow_build-.nJoqTYmt
/usr/local/bin/package.sh: line 22: wget: command not found
/usr/local/bin/package.sh: line 23: wget: command not found
/usr/local/bin/package.sh: line 24: wget: command not found
cp: docker-compose.yml: No such file or directory
/usr/local/bin/package.sh: line 28: virtualenv: command not found
/usr/local/bin/package.sh: line 29: /var/folders/sl/t4bb3syx4gx7lc3lwy1y4kn56g8jdc/T/rainbow_build-.nJoqTYmt/venv/bin/activate: No such file or directory
Collecting git+https://github.com/Natural-Intelligence/rainbow.git@rainbow_local_mode
  Cloning https://github.com/Natural-Intelligence/rainbow.git (to revision rainbow_local_mode) to /private/var/folders/sl/t4bb3syx4gx7lc3lwy1y4kn56g8jdc/T/pip-req-build-q252_sn4
  Running command git clone -q https://github.com/Natural-Intelligence/rainbow.git /private/var/folders/sl/t4bb3syx4gx7lc3lwy1y4kn56g8jdc/T/pip-req-build-q252_sn4
  Running command git checkout -b rainbow_local_mode --track origin/rainbow_local_mode
  Switched to a new branch 'rainbow_local_mode'
  Branch 'rainbow_local_mode' set up to track remote branch 'rainbow_local_mode' from 'origin'.
Building wheels for collected packages: rainbow
  Building wheel for rainbow (setup.py) ... done
  Created wheel for rainbow: filename=rainbow-0.0.1-py3-none-any.whl size=76768 sha256=c362663446b798fe2ef9f3cb397cd793b800f97942095edac6c9eb63196bfaa1
  Stored in directory: /private/var/folders/sl/t4bb3syx4gx7lc3lwy1y4kn56g8jdc/T/pip-ephem-wheel-cache-9y64knsw/wheels/4a/f7/e5/b3e1f572f70b30d68ffd2d426fa9ec806cad2a1bcd504b8c69
Successfully built rainbow
Installing collected packages: rainbow
Successfully installed rainbow-0.0.1
pip install --target="/var/folders/sl/t4bb3syx4gx7lc3lwy1y4kn56g8jdc/T/rainbow_build-.nJoqTYmt/zip_content" -r /var/folders/sl/t4bb3syx4gx7lc3lwy1y4kn56g8jdc/T/rainbow_build-.nJoqTYmt/zip_content/requirements-airflow.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/var/folders/sl/t4bb3syx4gx7lc3lwy1y4kn56g8jdc/T/rainbow_build-.nJoqTYmt/zip_content/requirements-airflow.txt'
/usr/local/bin/package.sh: line 36: my_requirements: command not found
rm: __init__.py: No such file or directory
  adding: docker/ (stored 0%)
  adding: docker/docker-compose.yml (deflated 60%)
  adding: bin/ (stored 0%)
  adding: bin/package.sh (deflated 65%)
  adding: bin/rainbow (deflated 61%)
  adding: tests/ (stored 0%)
  adding: tests/util/ (stored 0%)
  adding: tests/util/test_class_utils.py (deflated 68%)
  adding: tests/util/dag_test_utils.py (deflated 43%)
  adding: tests/util/test_pkg_1/ (stored 0%)
  adding: tests/util/test_pkg_1/__init__.py (deflated 43%)
  adding: tests/util/test_pkg_1/__pycache__/ (stored 0%)
  adding: tests/util/test_pkg_1/__pycache__/test_clazz_base.cpython-37.pyc (deflated 37%)
  adding: tests/util/test_pkg_1/__pycache__/__init__.cpython-37.pyc (deflated 15%)
  adding: tests/util/test_pkg_1/test_pkg_1_1/ (stored 0%)
  adding: tests/util/test_pkg_1/test_pkg_1_1/test_clazz_child_2.py (deflated 42%)
  adding: tests/util/test_pkg_1/test_pkg_1_1/test_pkg_1_1_2/ (stored 0%)
  adding: tests/util/test_pkg_1/test_pkg_1_1/test_pkg_1_1_2/__init__.py (stored 0%)
  adding: tests/util/test_pkg_1/test_pkg_1_1/test_pkg_1_1_2/__pycache__/ (stored 0%)
  adding: tests/util/test_pkg_1/test_pkg_1_1/test_pkg_1_1_2/__pycache__/test_clazz_leaf_2.cpython-37.pyc (deflated 42%)
  adding: tests/util/test_pkg_1/test_pkg_1_1/test_pkg_1_1_2/__pycache__/__init__.cpython-37.pyc (deflated 23%)
  adding: tests/util/test_pkg_1/test_pkg_1_1/test_pkg_1_1_2/test_clazz_leaf_2.py (deflated 38%)
  adding: tests/util/test_pkg_1/test_pkg_1_1/__init__.py (deflated 43%)
  adding: tests/util/test_pkg_1/test_pkg_1_1/__pycache__/ (stored 0%)
  adding: tests/util/test_pkg_1/test_pkg_1_1/__pycache__/test_clazz_child_1.cpython-37.pyc (deflated 38%)
  adding: tests/util/test_pkg_1/test_pkg_1_1/__pycache__/test_clazz_child_2.cpython-37.pyc (deflated 30%)
  adding: tests/util/test_pkg_1/test_pkg_1_1/__pycache__/__init__.cpython-37.pyc (deflated 18%)
  adding: tests/util/test_pkg_1/test_pkg_1_1/test_pkg_1_1_1/ (stored 0%)
  adding: tests/util/test_pkg_1/test_pkg_1_1/test_pkg_1_1_1/test_clazz_leaf_1.py (deflated 47%)
  adding: tests/util/test_pkg_1/test_pkg_1_1/test_pkg_1_1_1/__init__.py (deflated 43%)
  adding: tests/util/test_pkg_1/test_pkg_1_1/test_pkg_1_1_1/__pycache__/ (stored 0%)
  adding: tests/util/test_pkg_1/test_pkg_1_1/test_pkg_1_1_1/__pycache__/test_clazz_leaf_1.cpython-37.pyc (deflated 49%)
  adding: tests/util/test_pkg_1/test_pkg_1_1/test_pkg_1_1_1/__pycache__/__init__.cpython-37.pyc (deflated 23%)
  adding: tests/util/test_pkg_1/test_pkg_1_1/test_clazz_child_1.py (deflated 43%)
  adding: tests/util/test_pkg_1/test_clazz_base.py (deflated 43%)
  adding: tests/util/__init__.py (deflated 43%)
  adding: tests/util/__pycache__/ (stored 0%)
  adding: tests/util/__pycache__/test_class_utils.cpython-37.pyc (deflated 51%)
  adding: tests/util/__pycache__/dag_test_utils.cpython-37.pyc (deflated 27%)
  adding: tests/util/__pycache__/__init__.cpython-37.pyc (deflated 14%)
  adding: tests/__init__.py (deflated 43%)
  adding: tests/__pycache__/ (stored 0%)
  adding: tests/__pycache__/__init__.cpython-37.pyc (deflated 14%)
  adding: tests/runners/ (stored 0%)
  adding: tests/runners/__init__.py (deflated 43%)
  adding: tests/runners/__pycache__/ (stored 0%)
  adding: tests/runners/__pycache__/__init__.cpython-37.pyc (deflated 15%)
  adding: tests/runners/airflow/ (stored 0%)
  adding: tests/runners/airflow/tasks/ (stored 0%)
  adding: tests/runners/airflow/tasks/test_python.py (deflated 54%)
  adding: tests/runners/airflow/tasks/__init__.py (deflated 43%)
  adding: tests/runners/airflow/tasks/__pycache__/ (stored 0%)
  adding: tests/runners/airflow/tasks/__pycache__/test_python.cpython-37.pyc (deflated 40%)
  adding: tests/runners/airflow/tasks/__pycache__/__init__.cpython-37.pyc (deflated 14%)
  adding: tests/runners/airflow/tasks/defaults/ (stored 0%)
  adding: tests/runners/airflow/tasks/defaults/test_job_start.py (deflated 67%)
  adding: tests/runners/airflow/tasks/defaults/test_job_end.py (deflated 67%)
  adding: tests/runners/airflow/tasks/defaults/__init__.py (deflated 43%)
  adding: tests/runners/airflow/tasks/defaults/__pycache__/ (stored 0%)
  adding: tests/runners/airflow/tasks/defaults/__pycache__/test_job_start.cpython-37.pyc (deflated 51%)
  adding: tests/runners/airflow/tasks/defaults/__pycache__/test_job_end.cpython-37.pyc (deflated 52%)
  adding: tests/runners/airflow/tasks/defaults/__pycache__/__init__.cpython-37.pyc (deflated 14%)
  adding: tests/runners/airflow/operators/ (stored 0%)
  adding: tests/runners/airflow/operators/__init__.py (deflated 43%)
  adding: tests/runners/airflow/operators/__pycache__/ (stored 0%)
  adding: tests/runners/airflow/operators/__pycache__/__init__.cpython-37.pyc (deflated 14%)
  adding: tests/runners/airflow/dag/ (stored 0%)
  adding: tests/runners/airflow/dag/__init__.py (deflated 43%)
  adding: tests/runners/airflow/dag/__pycache__/ (stored 0%)
  adding: tests/runners/airflow/dag/__pycache__/test_rainbow_dags.cpython-37.pyc (deflated 49%)
  adding: tests/runners/airflow/dag/__pycache__/__init__.cpython-37.pyc (deflated 14%)
  adding: tests/runners/airflow/dag/test_rainbow_dags.py (deflated 66%)
  adding: tests/runners/airflow/__init__.py (deflated 43%)
  adding: tests/runners/airflow/__pycache__/ (stored 0%)
  adding: tests/runners/airflow/__pycache__/__init__.cpython-37.pyc (deflated 14%)
  adding: tests/runners/airflow/rainbow/ (stored 0%)
  adding: tests/runners/airflow/rainbow/helloworld/ (stored 0%)
  adding: tests/runners/airflow/rainbow/helloworld/hello_world.py (deflated 43%)
  adding: tests/runners/airflow/rainbow/helloworld/__init__.py (deflated 43%)
  adding: tests/runners/airflow/rainbow/helloworld/__pycache__/ (stored 0%)
  adding: tests/runners/airflow/rainbow/helloworld/__pycache__/__init__.cpython-37.pyc (deflated 14%)
  adding: tests/runners/airflow/rainbow/helloworld/__pycache__/hello_world.cpython-37.pyc (deflated 24%)
  adding: tests/runners/airflow/rainbow/myserver/ (stored 0%)
  adding: tests/runners/airflow/rainbow/myserver/__init__.py (deflated 43%)
  adding: tests/runners/airflow/rainbow/myserver/__pycache__/ (stored 0%)
  adding: tests/runners/airflow/rainbow/myserver/__pycache__/__init__.cpython-37.pyc (deflated 14%)
  adding: tests/runners/airflow/rainbow/myserver/__pycache__/my_server.cpython-37.pyc (deflated 24%)
  adding: tests/runners/airflow/rainbow/myserver/my_server.py (deflated 42%)
  adding: tests/runners/airflow/rainbow/__init__.py (deflated 43%)
  adding: tests/runners/airflow/rainbow/__pycache__/ (stored 0%)
  adding: tests/runners/airflow/rainbow/__pycache__/__init__.cpython-37.pyc (deflated 14%)
  adding: tests/runners/airflow/build/ (stored 0%)
  adding: tests/runners/airflow/build/python/ (stored 0%)
  adding: tests/runners/airflow/build/python/__init__.py (deflated 43%)
  adding: tests/runners/airflow/build/python/__pycache__/ (stored 0%)
  adding: tests/runners/airflow/build/python/__pycache__/test_python_image_builder.cpython-37.pyc (deflated 48%)
  adding: tests/runners/airflow/build/python/__pycache__/__init__.cpython-37.pyc (deflated 13%)
  adding: tests/runners/airflow/build/python/test_python_image_builder.py (deflated 65%)
  adding: tests/runners/airflow/build/test_build_rainbows.py (deflated 55%)
  adding: tests/runners/airflow/build/__init__.py (deflated 43%)
  adding: tests/runners/airflow/build/__pycache__/ (stored 0%)
  adding: tests/runners/airflow/build/__pycache__/test_build_rainbows.cpython-37.pyc (deflated 45%)
  adding: tests/runners/airflow/build/__pycache__/__init__.cpython-37.pyc (deflated 14%)
  adding: tests/runners/airflow/build/http/ (stored 0%)
  adding: tests/runners/airflow/build/http/python/ (stored 0%)
  adding: tests/runners/airflow/build/http/python/__init__.py (deflated 43%)
  adding: tests/runners/airflow/build/http/python/__pycache__/ (stored 0%)
  adding: tests/runners/airflow/build/http/python/__pycache__/test_python_server_image_builder.cpython-37.pyc (deflated 48%)
  adding: tests/runners/airflow/build/http/python/__pycache__/__init__.cpython-37.pyc (deflated 13%)
  adding: tests/runners/airflow/build/http/python/test_python_server_image_builder.py (deflated 64%)
  adding: tests/runners/airflow/build/http/__init__.py (deflated 43%)
  adding: tests/runners/airflow/build/http/__pycache__/ (stored 0%)
  adding: tests/runners/airflow/build/http/__pycache__/__init__.cpython-37.pyc (deflated 13%)
  adding: tests/runners/airflow/compiler/ (stored 0%)
  adding: tests/runners/airflow/compiler/__init__.py (deflated 43%)
  adding: tests/runners/airflow/compiler/__pycache__/ (stored 0%)
  adding: tests/runners/airflow/compiler/__pycache__/__init__.cpython-37.pyc (deflated 14%)
  adding: hello_rainbow.yml (deflated 70%)
  adding: rainbow-0.0.1.dist-info/ (stored 0%)
  adding: rainbow-0.0.1.dist-info/RECORD (deflated 78%)
  adding: rainbow-0.0.1.dist-info/LICENSE (deflated 66%)
  adding: rainbow-0.0.1.dist-info/WHEEL (stored 0%)
  adding: rainbow-0.0.1.dist-info/top_level.txt (stored 0%)
  adding: rainbow-0.0.1.dist-info/INSTALLER (stored 0%)
  adding: rainbow-0.0.1.dist-info/METADATA (deflated 59%)
  adding: rainbow/ (stored 0%)
  adding: rainbow/docker/ (stored 0%)
  adding: rainbow/docker/__init__.py (deflated 43%)
  adding: rainbow/docker/__pycache__/ (stored 0%)
  adding: rainbow/docker/__pycache__/__init__.cpython-37.pyc (deflated 14%)
  adding: rainbow/core/ (stored 0%)
  adding: rainbow/core/util/ (stored 0%)
  adding: rainbow/core/util/class_util.py (deflated 56%)
  adding: rainbow/core/util/__init__.py (deflated 43%)
  adding: rainbow/core/util/__pycache__/ (stored 0%)
  adding: rainbow/core/util/__pycache__/files_util.cpython-37.pyc (deflated 23%)
  adding: rainbow/core/util/__pycache__/class_util.cpython-37.pyc (deflated 38%)
  adding: rainbow/core/util/__pycache__/__init__.cpython-37.pyc (deflated 13%)
  adding: rainbow/core/util/files_util.py (deflated 46%)
  adding: rainbow/core/__init__.py (deflated 43%)
  adding: rainbow/core/__pycache__/ (stored 0%)
  adding: rainbow/core/__pycache__/environment.cpython-37.pyc (deflated 34%)
  adding: rainbow/core/__pycache__/__init__.cpython-37.pyc (deflated 14%)
  adding: rainbow/core/environment.py (deflated 50%)
  adding: rainbow/__init__.py (deflated 43%)
  adding: rainbow/__pycache__/ (stored 0%)
  adding: rainbow/__pycache__/__init__.cpython-37.pyc (deflated 14%)
  adding: rainbow/runners/ (stored 0%)
  adding: rainbow/runners/__init__.py (deflated 43%)
  adding: rainbow/runners/__pycache__/ (stored 0%)
  adding: rainbow/runners/__pycache__/__init__.cpython-37.pyc (deflated 15%)
  adding: rainbow/runners/airflow/ (stored 0%)
  adding: rainbow/runners/airflow/tasks/ (stored 0%)
  adding: rainbow/runners/airflow/tasks/__init__.py (deflated 43%)
  adding: rainbow/runners/airflow/tasks/delete_cloudformation_stack.py (deflated 46%)
  adding: rainbow/runners/airflow/tasks/__pycache__/ (stored 0%)
  adding: rainbow/runners/airflow/tasks/__pycache__/spark.cpython-37.pyc (deflated 35%)
  adding: rainbow/runners/airflow/tasks/__pycache__/sql.cpython-37.pyc (deflated 35%)
  adding: rainbow/runners/airflow/tasks/__pycache__/python.cpython-37.pyc (deflated 53%)
  adding: rainbow/runners/airflow/tasks/__pycache__/delete_cloudformation_stack.cpython-37.pyc (deflated 39%)
  adding: rainbow/runners/airflow/tasks/__pycache__/create_cloudformation_stack.cpython-37.pyc (deflated 39%)
  adding: rainbow/runners/airflow/tasks/__pycache__/__init__.cpython-37.pyc (deflated 14%)
  adding: rainbow/runners/airflow/tasks/create_cloudformation_stack.py (deflated 46%)
  adding: rainbow/runners/airflow/tasks/defaults/ (stored 0%)
  adding: rainbow/runners/airflow/tasks/defaults/default_task.py (deflated 48%)
  adding: rainbow/runners/airflow/tasks/defaults/job_end.py (deflated 53%)
  adding: rainbow/runners/airflow/tasks/defaults/__init__.py (deflated 43%)
  adding: rainbow/runners/airflow/tasks/defaults/__pycache__/ (stored 0%)
  adding: rainbow/runners/airflow/tasks/defaults/__pycache__/job_start.cpython-37.pyc (deflated 40%)
  adding: rainbow/runners/airflow/tasks/defaults/__pycache__/default_task.cpython-37.pyc (deflated 37%)
  adding: rainbow/runners/airflow/tasks/defaults/__pycache__/job_end.cpython-37.pyc (deflated 39%)
  adding: rainbow/runners/airflow/tasks/defaults/__pycache__/__init__.cpython-37.pyc (deflated 14%)
  adding: rainbow/runners/airflow/tasks/defaults/job_start.py (deflated 53%)
  adding: rainbow/runners/airflow/tasks/python.py (deflated 72%)
  adding: rainbow/runners/airflow/tasks/spark.py (deflated 46%)
  adding: rainbow/runners/airflow/tasks/sql.py (deflated 46%)
  adding: rainbow/runners/airflow/operators/ (stored 0%)
  adding: rainbow/runners/airflow/operators/cloudformation.py (deflated 77%)
  adding: rainbow/runners/airflow/operators/__init__.py (deflated 43%)
  adding: rainbow/runners/airflow/operators/__pycache__/ (stored 0%)
  adding: rainbow/runners/airflow/operators/__pycache__/job_status_operator.cpython-37.pyc (deflated 54%)
  adding: rainbow/runners/airflow/operators/__pycache__/kubernetes_pod_operator_with_input_output.cpython-37.pyc (deflated 46%)
  adding: rainbow/runners/airflow/operators/__pycache__/cloudformation.cpython-37.pyc (deflated 65%)
  adding: rainbow/runners/airflow/operators/__pycache__/__init__.cpython-37.pyc (deflated 14%)
  adding: rainbow/runners/airflow/operators/kubernetes_pod_operator_with_input_output.py (deflated 75%)
  adding: rainbow/runners/airflow/operators/job_status_operator.py (deflated 69%)
  adding: rainbow/runners/airflow/config/ (stored 0%)
  adding: rainbow/runners/airflow/config/standalone_variable_backend.py (deflated 48%)
  adding: rainbow/runners/airflow/config/__init__.py (stored 0%)
  adding: rainbow/runners/airflow/config/__pycache__/ (stored 0%)
  adding: rainbow/runners/airflow/config/__pycache__/standalone_variable_backend.cpython-37.pyc (deflated 31%)
  adding: rainbow/runners/airflow/config/__pycache__/__init__.cpython-37.pyc (deflated 15%)
  adding: rainbow/runners/airflow/dag/ (stored 0%)
  adding: rainbow/runners/airflow/dag/rainbow_dags.py (deflated 64%)
  adding: rainbow/runners/airflow/dag/__init__.py (deflated 43%)
  adding: rainbow/runners/airflow/dag/__pycache__/ (stored 0%)
  adding: rainbow/runners/airflow/dag/__pycache__/rainbow_dags.cpython-37.pyc (deflated 40%)
  adding: rainbow/runners/airflow/dag/__pycache__/__init__.cpython-37.pyc (deflated 14%)
  adding: rainbow/runners/airflow/__init__.py (deflated 43%)
  adding: rainbow/runners/airflow/__pycache__/ (stored 0%)
  adding: rainbow/runners/airflow/__pycache__/__init__.cpython-37.pyc (deflated 14%)
  adding: rainbow/runners/airflow/model/ (stored 0%)
  adding: rainbow/runners/airflow/model/task.py (deflated 48%)
  adding: rainbow/runners/airflow/model/__init__.py (deflated 43%)
  adding: rainbow/runners/airflow/model/__pycache__/ (stored 0%)
  adding: rainbow/runners/airflow/model/__pycache__/task.cpython-37.pyc (deflated 36%)
  adding: rainbow/runners/airflow/model/__pycache__/__init__.cpython-37.pyc (deflated 15%)
  adding: rainbow/build/ (stored 0%)
  adding: rainbow/build/image_builder.py (deflated 66%)
  adding: rainbow/build/__init__.py (deflated 43%)
  adding: rainbow/build/__pycache__/ (stored 0%)
  adding: rainbow/build/__pycache__/image_builder.cpython-37.pyc (deflated 53%)
  adding: rainbow/build/__pycache__/build_rainbows.cpython-37.pyc (deflated 46%)
  adding: rainbow/build/__pycache__/python.cpython-37.pyc (deflated 48%)
  adding: rainbow/build/__pycache__/__init__.cpython-37.pyc (deflated 14%)
  adding: rainbow/build/image/ (stored 0%)
  adding: rainbow/build/image/python/ (stored 0%)
  adding: rainbow/build/image/python/__init__.py (deflated 43%)
  adding: rainbow/build/image/python/__pycache__/ (stored 0%)
  adding: rainbow/build/image/python/__pycache__/python.cpython-37.pyc (deflated 43%)
  adding: rainbow/build/image/python/__pycache__/__init__.cpython-37.pyc (deflated 13%)
  adding: rainbow/build/image/python/python.py (deflated 52%)
  adding: rainbow/build/image/__init__.py (deflated 43%)
  adding: rainbow/build/image/__pycache__/ (stored 0%)
  adding: rainbow/build/image/__pycache__/__init__.cpython-37.pyc (deflated 13%)
  adding: rainbow/build/build_rainbows.py (deflated 67%)
  adding: rainbow/build/python.py (deflated 58%)
  adding: rainbow/build/service/ (stored 0%)
  adding: rainbow/build/service/service_image_builder.py (deflated 43%)
  adding: rainbow/build/service/python_server/ (stored 0%)
  adding: rainbow/build/service/python_server/python_server.py (deflated 55%)
  adding: rainbow/build/service/python_server/__init__.py (deflated 43%)
  adding: rainbow/build/service/python_server/rainbow_python_server.py (deflated 52%)
  adding: rainbow/build/service/python_server/__pycache__/ (stored 0%)
  adding: rainbow/build/service/python_server/__pycache__/rainbow_python_server.cpython-37.pyc (deflated 33%)
  adding: rainbow/build/service/python_server/__pycache__/python_server.cpython-37.pyc (deflated 49%)
  adding: rainbow/build/service/python_server/__pycache__/__init__.cpython-37.pyc (deflated 14%)
  adding: rainbow/build/service/__init__.py (deflated 43%)
  adding: rainbow/build/service/__pycache__/ (stored 0%)
  adding: rainbow/build/service/__pycache__/service_image_builder.cpython-37.pyc (deflated 17%)
  adding: rainbow/build/service/__pycache__/__init__.cpython-37.pyc (deflated 13%)
  adding: rainbow/monitoring/ (stored 0%)
  adding: rainbow/monitoring/__init__.py (deflated 43%)
  adding: rainbow/monitoring/__pycache__/ (stored 0%)
  adding: rainbow/monitoring/__pycache__/__init__.cpython-37.pyc (deflated 14%)
  adding: rainbow/sql/ (stored 0%)
  adding: rainbow/sql/__init__.py (deflated 43%)
  adding: rainbow/sql/__pycache__/ (stored 0%)
  adding: rainbow/sql/__pycache__/__init__.cpython-37.pyc (deflated 14%)
/Users/lior.schachter/dev/projects/liminal/dags
(base) pc-clementcohen:dags lior.schachter$ rainbow start
Loading image builder implementations..
Finished loading image builder implementations: {'rainbow.build.image.python.python.PythonImageBuilder': <class 'rainbow.build.image.python.python.PythonImageBuilder'>}
Loading service image builder implementations..
Finished loading service image builder implementations: {'rainbow.build.service.python_server.python_server.PythonServerImageBuilder': <class 'rainbow.build.service.python_server.python_server.PythonServerImageBuilder'>}
ERROR: .FileNotFoundError: [Errno 2] No such file or directory: '/Users/lior.schachter/dev/projects/liminal/home/docker-compose.yml'

**Comment by lior-schachter** [comment]
solved after installing wget:
brew install wget

I manage to start airflow but with no dags:
[2020-05-26 08:02:36,037] {{dagbag.py:271}} INFO - File /usr/local/airflow/dags/rainbows.zip assumed to contain no DAGs. Skipping.

Indeed no dags in the file. attached. 
[rainbows.zip](https://github.com/Natural-Intelligence/rainbow/files/4680765/rainbows.zip)

**Comment by assaf-pinhasi-khealth** [comment]
The log shows that you don't have virtualenv on your machine.
Zip creation relies on virtualenv to download all the packages which rainbow needs and pacakging them together in a zip with the rainbow dag parser.

do you think it's reasonable to request that people have virtualenv installed? 

alternatively we can build the .zip on the CI and have the deploy script just pull it fully baked.
It will be a bit more cumbersome for liminal developers but easier for users.

**Comment by lior-schachter** [comment]
I installed anaconda. I think it is too much to require also virtualenv from the users.
Lidor can build the zip with CI if needed.

**Comment by lior-schachter** [comment]
Or maybe just write it as a prerequisite.
@aviemzur what do you think ?

**Comment by naturalett** [comment]
**FYI:** The DAG is failing to import: from rainbow.core.util import class_util
The zip doesn't contain rainbow folder.
Need to take into consideration how to import with or without the rainbow.

**Comment by assapin** [comment]
if your package.sh didn't complete properly, the zip file with rainbow code
is not valid.
for it to complete you need to have wget and virtualenv installed, and to
clear $RAINBOW_HOME folder before starting the deployment.

**Comment by assapin** [comment]
I pushed a new version which performs the wget and pip installs inside a docker container.
now the user doesn't need to install anything on their computer (virtual env etc.)
seems to work for me, would be good if someone e.g. @naturalett verifies it works for them

**Comment by lior-schachter** [comment]
Still not working. Running rainbow deploy gets few errors:
/usr/local/bin/package.sh: line 28: virtualenv: command not found
/usr/local/bin/package.sh: line 29: /var/folders/sl/t4bb3syx4gx7lc3lwy1y4kn56g8jdc/T/rainbow_build-.S2lgsrIk/venv/bin/activate: No such file or directory
...

ERROR: spyder 4.0.1 requires pyqt5<5.13; python_version >= "3", which is not installed.
ERROR: spyder 4.0.1 requires pyqtwebengine<5.13; python_version >= "3", which is not installed.
ERROR: pytest-astropy 0.8.0 requires pytest-cov>=2.0, which is not installed.
ERROR: pytest-astropy 0.8.0 requires pytest-filter-subpackage>=0.1, which is not installed.
ERROR: astroid 2.3.3 requires typed-ast<1.5,>=1.4.0; implementation_name == "cpython" and python_version < "3.8", which is not installed.

however:
lior.schachter$ python --version
Python 3.7.6

After running: rainbow start, no DAGS in airflow.

In the log (attached), I get these log lines:

webserver_1  | [2020-06-02 14:09:33,536] {{dagbag.py:271}} INFO - File /usr/local/airflow/dags/rainbows.zip assumed to contain no DAGs. Skipping.
[rainbows.zip.LOG](https://github.com/Natural-Intelligence/rainbow/files/4717869/rainbows.zip.LOG)

see rainbow.zip.LOG attached (remove the LOG)
[output.LOG](https://github.com/Natural-Intelligence/rainbow/files/4717879/output.LOG)
.

Please advise

**Comment by assapin** [comment]
this installation log shows that you didn't update the project.
Here are the instructions I wrote in slack for how to re-test the new version which builds the zip inside docker:
1. pip uninstall rainbow
2. rm -rf ~/rainbow_home (or if you set it to a different location, delete it)
3. repeat installation process. 
Pay close attention to the requirements.txt in your "DAG" project.
if your DAG doesn't introduce new dependencies, requirements.txt should be empty
don't copy-paste it from the root of rainbow project or anything like that.

if it’s still not working, send me the installation logs and docker compose logs
